# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.7.0"

# variables
# the following default values are used. 
# values can be overwritten with the use of additional vagrantfiles.
$vm_gui = false
$vm_name = 'win81x64-pro'
$vm_memory = 2048
$vm_cpu = 2

Vagrant.configure('2') do |config|
    config.vm.define 'vagrant-win81x64-pro'
    config.vm.box = 'win81x64-pro'
    config.vm.communicator = 'winrm'
    config.vm.guest = 'windows'

    # admin user name and password
    config.winrm.username = 'vagrant'
    config.winrm.password = 'vagrant'

    # network settings
    config.vm.network :forwarded_port, guest: 3389, host: 3389, id: 'rdp', auto_correct: true
    config.vm.network :forwarded_port, guest: 5985, host: 5985, id: 'winrm', auto_correct: true

    # virtualbox
    config.vm.provider :virtualbox do |v, override|
        v.name = $vm_name
        v.gui = $vm_gui
        v.customize ['modifyvm', :id, '--memory', $vm_memory]
        v.customize ['modifyvm', :id, '--cpus', $vm_cpu]
        v.customize ['setextradata', 'global', 'GUI/SuppressMessages', 'all' ]
    end

    # vmware fusion
    config.vm.provider :vmware_fusion do |v, override|
        v.name = $vm_name
        v.gui = $vm_gui
        v.vmx['memsize'] = $vm_memory
        v.vmx['numvcpus'] = $vm_cpu
        v.vmx['ethernet0.virtualDev'] = 'vmxnet3'
        v.vmx['RemoteDisplay.vnc.enabled'] = 'false'
        v.vmx['RemoteDisplay.vnc.port'] = '5900'
        v.vmx['scsi0.virtualDev'] = 'lsisas1068'
    end

    # vmware workstation
    config.vm.provider :vmware_workstation do |v, override|
        v.name = $vm_name
        v.gui = $vm_gui
        v.vmx['memsize'] = $vm_memory
        v.vmx['numvcpus'] = $vm_cpu
        v.vmx['ethernet0.virtualDev'] = 'vmxnet3'
        v.vmx['RemoteDisplay.vnc.enabled'] = 'false'
        v.vmx['RemoteDisplay.vnc.port'] = '5900'
        v.vmx['scsi0.virtualDev'] = 'lsisas1068'
    end
end
